# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rack', '2.0.8'

gem 'middleman'
gem 'middleman-autoprefixer'
gem 'middleman-compass'
gem 'middleman-deploy', '2.0.0.pre.alpha'
gem 'middleman-livereload'
gem 'middleman-minify-html'

gem "middleman-imageoptim", :git => "https://github.com/plasticine/middleman-imageoptim", :branch => "master"

gem 'rails'
